# D Userland root path
USERLAND_ROOT 		= ../..

# Source files of the applicaion to be compiled
D_SRCS = $(wildcard *.d)

# Include the general applicaton makefile that compiles and builds the userland application
include $(USERLAND_ROOT)/AppMakefile.mk
