sudo: false
language: rust

# The language is a lie, but the C toolchain is available in the rust image. If
# we go the other way, then we have to slow builds by pulling in the rust
# toolchain manually.


# bors default configuration:
#branches:
#  only:
#    # This is where pull requests from "bors r+" are built.
#    - staging
#    # This is where pull requests from "bors try" are built.
#    - trying
#    # Uncomment this to enable building pull requests.
#    - master
#
# Instead, I think we just want to disable to bors temp branch
branches:
  except:
    - staging.tmp
    - trying.tmp



cache:
  cargo: true
  directories:
    - $HOME/gcc-arm-none-eabi-9-2019-q4-major
    - $HOME/gcc-riscv64-unknown-elf-8.3.0-ubuntu

os:
  - linux

rust:
  - stable

before_install:
  - ./.travis-install-gcc
  - export PATH="$PATH:$HOME/gcc-arm-none-eabi-9-2019-q4-major/bin"
  - export PATH="$PATH:$HOME/gcc-riscv64-unknown-elf-8.3.0-ubuntu/bin"
  - export PATH="$PATH:$HOME/uncrustify-uncrustify-0.65/build"

script:
  - pushd examples; RISCV=1 ./build_all.sh || exit; popd
  - pushd examples; ./format_all.sh || exit; popd
  - pushd examples/blink; make debug RAM_START=0x20004000 FLASH_INIT=0x30051 || exit; popd

